name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Test CLI functionality
      run: |
        # Test basic CLI
        node bin/tana --help
        
        # Test quick capture
        node bin/tana "CI test note" --dry-run
        
        # Test paste command
        node bin/tana paste "Test content" --stdout
        
        # Test config
        node bin/tana config show
        
        # Test validation (create test file)
        echo -e "%%tana%%\n- Test note #test" > test.txt
        node bin/tana validate --paste-file test.txt
        rm test.txt
    
    - name: Check package.json format
      run: node -e "JSON.parse(require('fs').readFileSync('package.json'))"